draw_config:
  draw_key_sides: true
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    '&ext_power EP_TOG': "🔌"
    '&caps_word': "🔠"
    '&bootloader': "💾"
    '&sys_reset': "🔄"
    '&reset_td': "🔄"
    '&dot_spc': ".⎵⇧"
    '&bt BT_SEL 0': 🛜1
    '&bt BT_SEL 1': 🛜2
    '&bt BT_SEL 2': 🛜3
    '&bt BT_SEL 3': 🛜4
    '&bt BT_SEL 4': 🛜5
    '&bt BT_NXT': 🛜🔼
    '&bt BT_PRV': 🛜🔽
    '&bt BT_CLR': 🛜❌
  sticky_label: sticky
  trans_legend:
    t: " "
    type: trans
  mark_alternate_layer_activators: false
  zmk_keycode_map:
    'LC(INS)': "📄"
    'LS(INS)': "📋"
    'LS(DEL)': "✂️"
    'LC(T)': "⌃T"
    'LC(B)': "⌃B"
    'LA(TAB)': "⌥ ⇥"
    'LS(LA(TAB))': "⇧⌥ ⇥"
    'RA(LBKT)': "š"
    'RA(RBKT)': "đ"
    'RA(SEMI)': "č"
    "RA(SQT)": "ć"
    'RA(BSLH)': "ž"
    'RA(E)': "€"
    'RG(N1)': "Sw1"
    'RG(N2)': "Sw2"
    'RG(N3)': "Sw3"
    'RG(N4)': "Sw4"
    'RG(N8)': "Sw8"
    'RG(N9)': "Sw9"
    'LG(LS(UP))': "WmP"
    'LC(1)': "P1"
    'LC(2)': "P2"
    'LC(3)': "P3"
    MEH: MEH
    'LC(LS(LALT))': "MEH"
    K_UNDO: "↩️"
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: '; <'
    COLON: ': >'
    SINGLE_QUOTE: ''''
    SQT: {tap: "'", shifted: '"'}
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: '<'
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    C_NEXT: ⏭️
    C_PREV: ⏮️
    C_PP: ⏯️
    C_MUTE: "🔇"
    C_VOL_DN: "🔉"
    C_VOL_UP: "🔊"
    C_BRI_UP: "🔆"
    C_BRI_DN: "🔅"
    K_CMENU: 🌍
    K_MENU: 🌍
    EP_TOG: "🔌"
    PG_UP: "⇞"
    HOME: "⇱"
    END: "⇲"
    PG_DN: "⇟"
    LEFT: "←"
    RIGHT: "→"
    KP_MULTIPLY: "*"
    UP: "↑"
    DOWN: "↓"
    KP_PLUS: "+"
    LCTRL: ⌃
    LALT: ⌥
    LGUI: 🐧
    LSHFT: ⇧
    RCTRL: ⌃
    LEFT_CONTROL: ⌃
    LEFT_ALT: ⌥
    LEFT_GUI: ⌘
    LEFT_SHFT: ⇧
    RALT: ⌥
    RGUI: 🐧
    RSHFT: ⇧
    RIGHT_CONTROL: ⌃
    RIGHT_ALT: ⌥
    RIGHT_GUI: ⌘
    RIGHT_SHFT: ⇧
    TAB: ⇥
    RET: '⏎'
    BSPC: ⌫
    DEL: ⌦
    SPACE: ⎵
    PSCRN: 🖨️
  zmk_combos: {}
